version: '3.8'
services:
  paldea:
    image: 'paldea-evolved:latest'
    build: 
      context: .
      dockerfile: Dockerfile
      expose:
      - "8080"
    ports:
      - '8080:8080'
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=8080
    depends_on:
      - mysql_db
    networks:
      - paldea
  paldea_mysql_db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: on-failure
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=mock-password
      - MYSQL_DATABASE=paldea
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3307:3306'
    volumes: 
      - db-config:/etc/mysql 
      - db-data:/var/lib/mysql 
    networks:
      - paldea

networks:
  paldea:

volumes:
  db-config:
  db-data:
    
